import "./globals.css";
import Navbar from "./Common/Navbar";
import Footer from "./Common/Footer";

export const metadata = {
  title: "Created by Ravi",
  description: "Generated by Rav next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <Navbar /> */}
        <main className="flex flex-col min-h-[calc(100vh)]">
          <div className="flex flex-1 flex-col h-full"> {children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
