import "./globals.css";

import Footer from "./Common/Footer";
import Script from "next/script";
import AOSInit from "./components/AOSInit";

export const metadata = {
  title: "Created by Ravi",
  description: "Generated by Rav next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </head>
      <body className={`antialiased`}>
        {/* <Navbar /> */}
        <main className="flex flex-col min-h-[calc(100vh)]">
          <div className="flex flex-1 flex-col h-full"> {children}</div>
          <Footer />
        </main>
      </body>
      <Script
        src="https://unpkg.com/aos@next/dist/aos.js"
        strategy="afterInteractive"
      />
      <AOSInit />
    </html>
  );
}
